name: Build Luma Mods

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        config: [Development-Debug, Development-Release, Test-Release, Publishing-Release]
        platform: [x64, Win32]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Clone vcpkg
      run: git clone https://github.com/microsoft/vcpkg.git

    - name: Bootstrap vcpkg
      run: .\vcpkg\bootstrap-vcpkg.bat

    #exclusively for Prey. Ideally it should find the vcpkg.json automatically
    - name: Install vcpkg packages
      run: |
        .\vcpkg\vcpkg install --triplet x64-windows --manifest-root=./Source/Games/Prey --debug
#        .\vcpkg\vcpkg install --triplet x86-windows --manifest-root=./Source/Games/Prey
      continue-on-error: true

    - name: Integrate vcpkg with MSBuild
      run: .\vcpkg\vcpkg integrate install

    - name: Build Luma.sln ${{ matrix.config }}|${{ matrix.platform }}
      run: msbuild Luma.sln /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.platform }}

    - name: Upload all EXEs and DLLs from binaries folders
      uses: actions/upload-artifact@v4
      with:
        name: Binaries-${{ matrix.config }}-${{ matrix.platform }}
        path: |
          **/${{ matrix.platform }}/${{ matrix.config }}/*.addon
          **/${{ matrix.platform }}/${{ matrix.config }}/*.exe
          **/${{ matrix.platform }}/${{ matrix.config }}/*.dll
          **/${{ matrix.platform }}/${{ matrix.config }}/*.pdb
