jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Development-Debug, Development-Release, Test-Release, Publishing-Release]
        platform: [x64, Win32]
    steps:
      # Build steps here...

      - name: Upload DLLs
        uses: actions/upload-artifact@v4
        with:
          name: Binaries-${{ matrix.config }}-${{ matrix.platform }}
          path: |
            **/${{ matrix.platform }}-${{ matrix.config }}/*.addon

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: Binaries-*
          merge-multiple: true  # puts all files in a single folder

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ github.run_number }}
          name: Nightly Build ${{ github.run_number }}
          body: |
            This is an automated release of all DLLs from matrix builds.
          files: |
            *.addon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
